import { NextApiResponse } from "next";

const { OpenAI } = require("openai");

export async function POST(req: any, res: NextApiResponse) {
  const openai = new OpenAI({
    apiKey: process.env.OPEN_AI_API_KEY,
  });

  const response = await openai.chat.completions.create({
    model: "gpt-3.5-turbo",
    messages: [
      { role: "system", content: "You are a helpful assistant." },
      { role: "user", content: "Who won the world series in 2020?" },
      //   { role: "assistant", content: "The Los Angeles Dodgers." }, text generated by the model previously and used to continue the conversation
      //   { role: "user", content: "Where was it played?" }, text generated by the user and used to continue the conversation
    ],
    max_tokens: 50,
    n: 1,
    stop: null,
    temperature: 1,
  });

  res.status(200).json({ answer: response.data.choices });
}
